"""add_insight_fields

Revision ID: 59cfadd5cbd5
Revises: 749c4e69fab3
Create Date: 2026-06-14 18:34:11.668793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59cfadd5cbd5'
down_revision: Union[str, None] = '749c4e69fab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_architecture_reports', sa.Column('relationship_pattern', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('story_engine_summary', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('dramatic_potential', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('inciting_relationship', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('central_conflict', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('story_beginning_summary', sa.Text(), nullable=True))
    op.add_column('relationship_architecture_reports', sa.Column('relationship_risk', sa.Text(), nullable=True))
    op.add_column('relationship_architecture_reports', sa.Column('relationship_pattern', sa.Text(), nullable=True))
    op.add_column('relationship_architecture_reports', sa.Column('consequence_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationship_architecture_reports', 'consequence_summary')
    op.drop_column('relationship_architecture_reports', 'relationship_pattern')
    op.drop_column('relationship_architecture_reports', 'relationship_risk')
    op.drop_column('character_architecture_reports', 'story_beginning_summary')
    op.drop_column('character_architecture_reports', 'central_conflict')
    op.drop_column('character_architecture_reports', 'inciting_relationship')
    op.drop_column('character_architecture_reports', 'dramatic_potential')
    op.drop_column('character_architecture_reports', 'story_engine_summary')
    op.drop_column('character_architecture_reports', 'relationship_pattern')
    # ### end Alembic commands ###
