"""add dramatic architecture fields and custom overrides

Revision ID: 63f648222820
Revises: 8e187b2dfafb
Create Date: 2026-06-16 17:14:56.220980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f648222820'
down_revision: Union[str, None] = '8e187b2dfafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_architecture_reports', sa.Column('narrative_consequence_custom', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('conflict_created_custom', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('pressure_point', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('pressure_point_custom', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('transformation_path', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('transformation_path_custom', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('custom_outdated_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_architecture_reports', 'custom_outdated_fields')
    op.drop_column('character_architecture_reports', 'transformation_path_custom')
    op.drop_column('character_architecture_reports', 'transformation_path')
    op.drop_column('character_architecture_reports', 'pressure_point_custom')
    op.drop_column('character_architecture_reports', 'pressure_point')
    op.drop_column('character_architecture_reports', 'conflict_created_custom')
    op.drop_column('character_architecture_reports', 'narrative_consequence_custom')
    # ### end Alembic commands ###
