"""Initial schema

Revision ID: 749c4e69fab3
Revises: 
Create Date: 2026-06-14 16:20:47.209120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '749c4e69fab3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_questions',
    sa.Column('flow_type', sa.String(length=50), nullable=False),
    sa.Column('question_key', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('suggested_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_questions_flow_type'), 'discovery_questions', ['flow_type'], unique=False)
    op.create_index(op.f('ix_discovery_questions_question_key'), 'discovery_questions', ['question_key'], unique=True)
    op.create_table('stories',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('one_sentence_premise', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_title'), 'stories', ['title'], unique=False)
    op.create_table('characters',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('archetype', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_story_id'), 'characters', ['story_id'], unique=False)
    op.create_table('character_architecture_reports',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('character_core', sa.Text(), nullable=True),
    sa.Column('emotional_wound', sa.Text(), nullable=True),
    sa.Column('deepest_fear', sa.Text(), nullable=True),
    sa.Column('protective_lie', sa.Text(), nullable=True),
    sa.Column('behavior', sa.Text(), nullable=True),
    sa.Column('narrative_consequence', sa.Text(), nullable=True),
    sa.Column('conflict_created', sa.Text(), nullable=True),
    sa.Column('transformation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('relationships',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('character_a_id', sa.UUID(), nullable=False),
    sa.Column('character_b_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_character_a_id'), 'relationships', ['character_a_id'], unique=False)
    op.create_index(op.f('ix_relationships_character_b_id'), 'relationships', ['character_b_id'], unique=False)
    op.create_index(op.f('ix_relationships_story_id'), 'relationships', ['story_id'], unique=False)
    op.create_table('discovery_answers',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('relationship_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_answer', sa.Text(), nullable=True),
    sa.Column('custom_answer', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['discovery_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_answers_character_id'), 'discovery_answers', ['character_id'], unique=False)
    op.create_index(op.f('ix_discovery_answers_question_id'), 'discovery_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_discovery_answers_relationship_id'), 'discovery_answers', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_discovery_answers_story_id'), 'discovery_answers', ['story_id'], unique=False)
    op.create_table('relationship_architecture_reports',
    sa.Column('relationship_id', sa.UUID(), nullable=False),
    sa.Column('current_result', sa.Text(), nullable=True),
    sa.Column('emotional_effect', sa.Text(), nullable=True),
    sa.Column('story_consequence', sa.Text(), nullable=True),
    sa.Column('current_relationship_risk', sa.Text(), nullable=True),
    sa.Column('turning_point', sa.Text(), nullable=True),
    sa.Column('relationship_law', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_architecture_reports')
    op.drop_index(op.f('ix_discovery_answers_story_id'), table_name='discovery_answers')
    op.drop_index(op.f('ix_discovery_answers_relationship_id'), table_name='discovery_answers')
    op.drop_index(op.f('ix_discovery_answers_question_id'), table_name='discovery_answers')
    op.drop_index(op.f('ix_discovery_answers_character_id'), table_name='discovery_answers')
    op.drop_table('discovery_answers')
    op.drop_index(op.f('ix_relationships_story_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_character_b_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_character_a_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_table('character_architecture_reports')
    op.drop_index(op.f('ix_characters_story_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_stories_title'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_discovery_questions_question_key'), table_name='discovery_questions')
    op.drop_index(op.f('ix_discovery_questions_flow_type'), table_name='discovery_questions')
    op.drop_table('discovery_questions')
    # ### end Alembic commands ###
