"""add stale report tracking

Revision ID: 8e187b2dfafb
Revises: da461b229db2
Create Date: 2026-06-15 18:43:24.322586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e187b2dfafb'
down_revision: Union[str, None] = 'da461b229db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_architecture_reports', sa.Column('is_stale', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('character_architecture_reports', sa.Column('stale_reason', sa.Text(), nullable=True))
    op.add_column('relationship_architecture_reports', sa.Column('is_stale', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('relationship_architecture_reports', sa.Column('stale_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationship_architecture_reports', 'stale_reason')
    op.drop_column('relationship_architecture_reports', 'is_stale')
    op.drop_column('character_architecture_reports', 'stale_reason')
    op.drop_column('character_architecture_reports', 'is_stale')
    # ### end Alembic commands ###
