"""add_pattern_metadata_to_reports

Revision ID: b4f1d475d1bd
Revises: 63f648222820
Create Date: 2026-06-17 08:45:26.686200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f1d475d1bd'
down_revision: Union[str, None] = '63f648222820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_architecture_reports', sa.Column('pattern_detected', sa.Text(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('pattern_version', sa.Integer(), nullable=True))
    op.add_column('character_architecture_reports', sa.Column('composition_detected', sa.Text(), nullable=True))
    op.add_column('relationship_architecture_reports', sa.Column('pattern_detected', sa.Text(), nullable=True))
    op.add_column('relationship_architecture_reports', sa.Column('pattern_version', sa.Integer(), nullable=True))
    op.add_column('relationship_architecture_reports', sa.Column('composition_detected', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationship_architecture_reports', 'composition_detected')
    op.drop_column('relationship_architecture_reports', 'pattern_version')
    op.drop_column('relationship_architecture_reports', 'pattern_detected')
    op.drop_column('character_architecture_reports', 'composition_detected')
    op.drop_column('character_architecture_reports', 'pattern_version')
    op.drop_column('character_architecture_reports', 'pattern_detected')
    # ### end Alembic commands ###
