"""add discovery events

Revision ID: c96cd62e2701
Revises: 59cfadd5cbd5
Create Date: 2026-06-14 19:07:22.094314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96cd62e2701'
down_revision: Union[str, None] = '59cfadd5cbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_events',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('relationship_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_events_character_id'), 'discovery_events', ['character_id'], unique=False)
    op.create_index(op.f('ix_discovery_events_created_at'), 'discovery_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_discovery_events_event_type'), 'discovery_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_discovery_events_relationship_id'), 'discovery_events', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_discovery_events_story_id'), 'discovery_events', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovery_events_story_id'), table_name='discovery_events')
    op.drop_index(op.f('ix_discovery_events_relationship_id'), table_name='discovery_events')
    op.drop_index(op.f('ix_discovery_events_event_type'), table_name='discovery_events')
    op.drop_index(op.f('ix_discovery_events_created_at'), table_name='discovery_events')
    op.drop_index(op.f('ix_discovery_events_character_id'), table_name='discovery_events')
    op.drop_table('discovery_events')
    # ### end Alembic commands ###
