"""add event_metadata to discovery_events

Revision ID: da461b229db2
Revises: c96cd62e2701
Create Date: 2026-06-15 16:52:51.442957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da461b229db2'
down_revision: Union[str, None] = 'c96cd62e2701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery_events', sa.Column('event_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False))
    op.alter_column('discovery_events', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('discovery_events', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discovery_events', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('discovery_events', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('discovery_events', 'event_metadata')
    # ### end Alembic commands ###
