"""Add users and story ownership

Revision ID: fcd340248b19
Revises: b4f1d475d1bd
Create Date: 2026-06-17 10:16:50.452578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = 'fcd340248b19'
down_revision: Union[str, None] = 'b4f1d475d1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('stories', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    op.create_foreign_key('fk_stories_users_id', 'stories', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # Data Backfill for Development
    dev_user_id = uuid.uuid4()
    now = datetime.now(timezone.utc)
    op.execute(
        sa.text(
            f"INSERT INTO users (id, email, password_hash, display_name, is_active, created_at, updated_at) "
            f"VALUES ('{dev_user_id}', 'dev@storyarchitect.local', '!DISABLED!', 'Development User', false, '{now}', '{now}')"
        )
    )
    op.execute(sa.text(f"UPDATE stories SET user_id = '{dev_user_id}' WHERE user_id IS NULL"))

    op.alter_column('stories', 'user_id', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stories_users_id', 'stories', type_='foreignkey')
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.drop_column('stories', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
